<?
  include_once ("../../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["wid", "cid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $query = "insert into user_work (user_id, work_id, composer_id, favorite) values ('{$_REQUEST["id"]}', '{$_REQUEST["wid"]}', '{$_REQUEST["cid"]}', 1)
                  on duplicate key update favorite = 1";

      mysqli_query ($mysql, $query);

      $apireturn["list"] = worklist ($_REQUEST["id"]);
      $apireturn["composerworks"] = workcomposerlist ($_REQUEST["id"]);
      $apireturn["status"]["success"] = "true";
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["work"]["id"] = $_REQUEST["wid"];
  }

  shell_exec ("rm ". WEBDIR. "/user/{$_REQUEST["id"]}/ -rf");
  echo apireturn ($apireturn);
