<?= file_get_contents ("template.html"); ?>

  <form method="post" action="/dyn/recording/edit/" enctype="multipart/form-data">
    <label for="rid">Recording ID:</label>
    <input type="text" name="rid" />
    <label for="work_id">Work ID:</label>
    <input type="text" name="work_id" />
    <label for="label">Label:</label>
    <input type="text" name="label" />
    <label for="year">Year:</label>
    <input type="text" name="year" />
    <label for="recommended">Recommended:</label>
    <input type="text" name="recommended" />
    <label for="compilation">Compilation:</label>
    <input type="text" name="compilation" />
    <label for="upc">UPC:</label>
    <input type="text" name="upc" />
    <label for="spotify_albumid">Spotify Album ID:</label>
    <input type="text" name="spotify_albumid" />
    <label for="spotify_imgurl">Spotify Cover URL:</label>
    <input type="text" name="spotify_imgurl" />
    <label for="uni_id">Uni ID:</label>
    <input type="text" name="uni_id" />
    <label for="performers">Performers:</label>
    <textarea name="performers">
      [
        {"performer":"Semyon Bychkov","role":"Conductor"},
        {"performer":"Vienna Philharmonic Orchestra","role":"Orchestra"}
      ]
    </textarea>
    <label for="tracks">Tracks:</label>
    <textarea name="tracks">
      [
        {"cd":"1","position":"0","length":"952","title":"I. Lebhaft","spotify_trackid":"0W2BjjcnvY36hUPWWLVaFN"},
        {"cd":"1","position":"1","length":"1091","title":"II. Allegretto con variazioni","spotify_trackid":"125EjvHYbfbHZ2UI5N0S0v"},
        {"cd":"1","position":"2","length":"850","title":"III. Finale","spotify_trackid":"5fYKCQGB7KkSr8vvj473dk"}
      ]
    </textarea>
    <label for="id">User ID:</label>
    <input type="text" name="id" value="1232501018" />
    <label for="auth">Auth:</label>
    <input type="text" name="auth" value="<?=md5 (floor ((time() + (60 * 1)) / (60 * 5)). "-1232501018-b42e59dbc4554d07c64fab871dfbb7b4")?>" />
    <button type="submit">Submit</button>
  </form>
</body>
