<?= file_get_contents ("template.html"); ?>

  <form method="post" action="/dyn/composer/new/" enctype="multipart/form-data">
    <label for="name">Name:</label>
    <input type="text" name="name" />
    <label for="complete_name">Complete name:</label>
    <input type="text" name="complete_name" />
    <label for="birth">Birth:</label>
    <input type="text" name="birth" />
    <label for="Death">Death:</label>
    <input type="text" name="death" />
    <label for="country">Country:</label>
    <input type="text" name="country" />
    <label for="epoch">Epoch:</label>
    <input type="text" name="epoch" />
    <label for="recommended">Recommended:</label>
    <input type="text" name="recommended" />
    <label for="uni_id">Uni ID:</label>
    <input type="text" name="uni_id" />
    <label for="id">User ID:</label>
    <input type="text" name="id" value="1232501018" />
    <label for="auth">Auth:</label>
    <input type="text" name="auth" value="<?=md5 (floor ((time() + (60 * 1)) / (60 * 5)). "-1232501018-b42e59dbc4554d07c64fab871dfbb7b4")?>" />
    <button type="submit">Submit</button>
  </form>
</body>
