<?
  include_once ("../../../lib/inc.php");
  global $timesteps;

  $goquery = true;

  // new compatible sets

  $_REQUEST["originalset"] = $_REQUEST["set"];

  if ($_REQUEST["set"] != "1")
  {
    $_REQUEST["wid"] = "at*". $_REQUEST["set"];
    $_REQUEST["set"] = 1;
  }

  if (stristr ($_REQUEST["wid"], "at*"))
  {
    // spotify work

    $goquery = true;
    $work_spotid = str_replace ("at*", "", $_REQUEST["wid"]);
    $apireturn["status"] = Array ("success"=>"true", "source"=>"ext", "market"=>$_REQUEST["market"]);

    // fetching album and looking for the track
    
    $spot = albumspotify ($_REQUEST["aid"], $_REQUEST["country"]);

    foreach ($spot["items"] as $recording)
    {
      foreach ($recording["tracks"] as $track)
      {
        if ($track["spotify_trackid"] == $work_spotid)
        {
          $apireturn["work"] = $recording["work"];
          $spot["items"] = $recording["tracks"];
        }
      }
    }

    //$apireturn["work"] = ["id" => $_REQUEST["wid"], "title" => $spot["extras"]["work"]["title"], "subtitle" => $spot["extras"]["work"]["subtitle"], "composer" => $spot["extras"]["composer"], "genre"=>"None"];
    
    $apireturn["recording"] = Array
      (
        "spotify_albumid"=>$_REQUEST["aid"],
        "spotify_tracks"=>Array (),
        "performers"=>Array (),
        "tracks"=>Array (),
      );
  }
  else
  {
    // open opus work

    $work = openopusdownparse ("work/detail/{$_REQUEST["wid"]}.json");
    
    if (!$work)
    {
      // if work doesn't exist, return an error

      $apireturn["status"] = Array ("success"=>"false", "error"=>"Work not found");
      $goquery = false;
    }
    else
    {
      // work exists

      $work["recording"]["spotify_albumid"] = $_REQUEST["aid"];

      $apireturn["work"] = $work["work"];
      $apireturn["work"]["composer"] = $work["composer"];
      
      $apireturn["recording"] = Array
        (
          "spotify_albumid"=>$_REQUEST["aid"],
          "spotify_tracks"=>Array (),
          "performers"=>Array (),
          "tracks"=>Array (),
        );

      // fetching data from spotify

      $apireturn["recording"]["length"] = 0;
      $apireturn["status"] = Array ("success"=>"true", "source"=>"ext");

      $spot = fetchspotify ($work, "tracks", $_REQUEST["market"]);
    }
  }

  if ($goquery)
  {
    // guessing the performers

    $perfs = openopusdownparse ("dyn/performer/list/", ["names"=>json_encode (end($spot["items"])["performers"])]);
    $rldb = $perfs["performers"]["digest"];

    // adding extradata to spotify results

    $spot = extradata ($spot, Array ("wid"=>$_REQUEST["wid"], "aid"=>$_REQUEST["aid"], "set"=>$_REQUEST["set"]));

    if ($spot["extras"]["observation"]) $apireturn["work"]["subtitle"] = $spot["extras"]["observation"];

    $spotres = $spot["items"];
    $apireturn["status"]["stats"] = $spot["stats"];
    $index = 0;

    foreach ($spotres as $tart)
    {
      $trinsert[] = Array
      (
        "cd" => $tart["cd"],
        "index" => $index++,
        "position" => $tart["position"],
        "length" => $tart["length"],
        "title" => $tart["title"],
        "spotify_trackid" => $tart["spotify_trackid"]
      );

      $apireturn["recording"]["tracks"][] = end ($trinsert);
      $apireturn["recording"]["length"] += end($trinsert)["length"];
    }

    $apireturn["recording"]["verified"] = $spot["extras"]["verified"] ? "true" : "false";
    $apireturn["recording"]["cover"] = $spot["extras"]["cover"];
    $apireturn["recording"]["set"] = (String) $_REQUEST["set"];
    $apireturn["recording"]["year"] = explode ("-", $spot["extras"]["year"])[0];
    $apireturn["recording"]["markets"] = $spot["extras"]["markets"];
    $apireturn["recording"]["label"] = $spot["extras"]["label"];
    $apireturn["recording"]["performers"] = (end($spotres)["extraperformers"]) ? orderperformers (end($spotres)["extraperformers"]): allperformers (end($spotres)["performers"], $rldb, $apireturn["work"]["composer"]["complete_name"]);
  }

  // setting auxiliary trackset & setting tracks starting points

  if (isset ($apireturn["recording"]["tracks"]) && $apireturn["recording"]["spotify_albumid"])
  {
    $acctiming = 0;

    foreach ($apireturn["recording"]["tracks"] as $trid => $track)
    {
      $apireturn["recording"]["tracks"][$trid]["starting_point"] = $acctiming;
      $acctiming += $track["length"];
      $apireturn["recording"]["spotify_tracks"][] = "spotify:track:". $apireturn["recording"]["tracks"][$trid]["spotify_trackid"];
    }
  }

  if ($_REQUEST["market"])
  {
    echo savecache ("/recording/{$_REQUEST["market"]}/detail/work/{$_REQUEST["wid"]}/album/{$_REQUEST["aid"]}/{$_REQUEST["set"]}.json", apireturn ($apireturn));
  }
  else
  {
    echo savecache ("/recording/detail/work/{$_REQUEST["wid"]}/album/{$_REQUEST["aid"]}/{$_REQUEST["set"]}.json", apireturn ($apireturn));
  }
