<?
  include_once ("../../../lib/inc.php");
  global $timesteps;

  /*

  select playlist_id, concat(work.id,'-',recording.spotify_albumid,'-',recording.subset) as id, recording.subset, recording.spotify_albumid, work.id as work, work.genre, composer.epoch, composer.id as composer, composer.name, work.title, work.genre, spotify_imgurl as cover, performer, role from recording, recording_performer, composer, work, playlist_recording where composer.id = composer_id and work.id = recording.work_id and recording_performer.work_id = recording.work_id and recording_performer.subset = recording.subset and recording_performer.spotify_albumid = recording.spotify_albumid and playlist_recording.work_id = recording.work_id and playlist_recording.subset = recording.subset and playlist_recording.spotify_albumid = recording.spotify_albumid order by position desc, composer.name asc, work.title asc, recording.spotify_albumid asc, recording.subset asc

  */

  // playlists

  /*

  $play = mysqlfetch ($mysql, "select * FROM user_recording where favorite=1 order by user_id, spotify_albumid");

  foreach ($play as $pl)
  {
    $work = mysqlfetch ($mysql, "select namesearch, epoch, genre, composer_id as composer, composer.name, composer.complete_name, title, ifnull (lower(searchtitle),lower(title)) searchtitle, lower(alternatetitles) alternatetitles, work.id from work, composer where work.id = {$pl["work_id"]} and composer.id=work.composer_id");
        
    if ($work[0]["searchtitle"] == strtolower ($work[0]["title"]))
    {
      $work[0]["searchtitle"] = worksimplifier ($work[0]["title"]);
    }

    $work[0]["spotify_albumid"] = $pl["spotify_albumid"];
    $spot = fetchspotify ($work, "tracks");

    if (sizeof ($spot["items"]) <= 0)
    {
      preg_match_all (CATALOGUE_REGEX, $work[0]["title"], $matches);
      $work[0]["title"] = str_replace ($matches[0][0], "", $work[0]["title"]);
      $spot = fetchspotify ($work, "tracks");
    }
    
    if (sizeof (end($spot["items"])["performers"]))
    {
      $request = Array 
        (
          "wid" => $pl["work_id"],
          "aid" => $pl["spotify_albumid"],
          "set" => $pl["subset"],
          "cover" => $spot["extras"]["cover"],
          "performers" => json_encode (end($spot["items"])["performers"])
        );

      print_r ($request);
      insertrecording ($request);

      sleep (2);
    }
  }

  */