<?
  include_once ("../../../lib/inc.php");

  // try to find the recording

  $recordings = mysqlfetch ($mysql, "select concat(work.id,'-',recording.spotify_albumid,'-',recording.subset) as id, recording.subset, recording.spotify_albumid, work.id as work, work.genre, composer.epoch, composer.id as composer, composer.name, work.title, work.genre, spotify_imgurl as cover, performer, role from recording, recording_performer, composer, work, playlist_recording where composer.id = composer_id and work.id = recording.work_id and playlist_id = '{$_REQUEST["id"]}' and recording_performer.work_id = recording.work_id and recording_performer.subset = recording.subset and recording_performer.spotify_albumid = recording.spotify_albumid and playlist_recording.work_id = recording.work_id and playlist_recording.subset = recording.subset and playlist_recording.spotify_albumid = recording.spotify_albumid order by position desc, composer.name asc, work.title asc, recording.spotify_albumid asc, recording.subset asc");

  if (!$recordings)
  {
    // if the recording doesn't exist, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No recordings found");
  }
  else
  {
    // playlist details

    $query = "select playlist.id as id, playlist.name as name, user.name as owner, user.spotify_id as owner_id from playlist, user where user_id=user.spotify_id and playlist.id = '{$_REQUEST["id"]}'";
    $playlist = mysqlfetch ($mysql, $query);
    $apireturn["playlist"] = Array 
      (
        "id" => $playlist[0]["id"],
        "name" => $playlist[0]["name"],
        "owner" => Array 
          (
            "id" => $playlist[0]["owner_id"],
            "name" => $playlist[0]["owner"]
          )
      );

    // recordings

    foreach ($recordings as $rec)
    {
      if ($lastid != $rec["id"])
      {
        $id = $id + 1;
        $apireturn["recordings"][$id] = Array
          (
            "spotify_albumid" => $rec["spotify_albumid"],
            "set" => $rec["subset"],
            "cover" => $rec["cover"]
          );
      }

      $apireturn["recordings"][$id]["performers"][] = Array ("name"=>$rec["performer"],"role"=>$rec["role"]);
      $apireturn["recordings"][$id]["work"] = Array
        (
          "composer"=>Array
            (
              "id"=>$rec["composer"],
              "name"=>$rec["name"],
              "epoch"=>$rec["epoch"]
            ),
           "id"=>$rec["work"],
           "title"=>$rec["title"],
           "genre"=>$rec["genre"],
        );

      $lastid = $rec["id"];
    }
  }

  if (isset ($apireturn["recordings"]))
  {
    $apireturn["status"]["rows"] = sizeof ($apireturn["recordings"]);
  }

  echo savecache ("/recording/list/playlist/{$_REQUEST["id"]}.json", apireturn ($apireturn));
