<?
  include_once ("../../../lib/inc.php");

  // try to find the recording

  $recordings = mysqlfetch ($mysql, "select spotify_absent, recording.uni_id as uni_id, spotify_albumid, work.id as work, work.genre, composer.epoch, composer.id as composer, composer.name, work.title, work.genre, recording.id, label, date_format (recording.year, '%Y') as year, upc, uni_imgurl as cover, performer, role from recording, recording_performer, composer, work, playlist_recording where composer.id = composer_id and work.id = work_id and recording.id = playlist_recording.recording_id and recording_performer.recording_id = recording.id and playlist_id = '{$_REQUEST["id"]}' order by position desc, composer.name asc, work.title asc, recording.id asc");

  if (!$recordings)
  {
    // if the recording doesn't exist, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No recordings found");
  }
  else
  {
    // playlist details

    $query = "select playlist.id as id, playlist.name as name, user.name as owner, user.spotify_id as owner_id from playlist, user where user_id=user.spotify_id and playlist.id = '{$_REQUEST["id"]}'";
    $playlist = mysqlfetch ($mysql, $query);
    $apireturn["playlist"] = Array 
      (
        "id" => $playlist[0]["id"],
        "name" => $playlist[0]["name"],
        "owner" => Array 
          (
            "id" => $playlist[0]["owner_id"],
            "name" => $playlist[0]["owner"]
          )
      );

    // recordings

    foreach ($recordings as $rec)
    {
      if ($lastid != $rec["id"])
      {
        $id = $id + 1;
        $apireturn["recordings"][$id] = Array
          (
            "id" => $rec["id"],
            "label" => $rec["label"],
            "year" => $rec["year"],
            "upc" => $rec["upc"],
            "cover" => PUBLIC_URL. "/cover/". $rec["id"]. "|". str_replace ("/", "-", str_replace ("/images/coverart/", "", $rec["cover"])),
            "historical" => (in_array ($rec["label"], $historical_labels)) ? "true" : "false",
            "compilation" => ($rec["compilation"]) ? "true" : "false"
          );
      }

      $apireturn["recordings"][$id]["performers"][] = Array ("name"=>$rec["performer"],"role"=>$rec["role"]);
      $apireturn["recordings"][$id]["work"] = Array
        (
          "composer"=>Array
            (
              "id"=>$rec["composer"],
              "name"=>$rec["name"],
              "epoch"=>$rec["epoch"]
            ),
           "id"=>$rec["work"],
           "title"=>$rec["title"],
           "genre"=>$rec["genre"],
        );

      $lastid = $rec["id"];
    }
  }

  if (isset ($apireturn["recordings"]))
  {
    $apireturn["status"]["rows"] = sizeof ($apireturn["recordings"]);
  }

  echo savecache ("/recording/list/playlist/{$_REQUEST["id"]}.json", apireturn ($apireturn));
