<?
  include_once ("../../../lib/inc.php");

  // try to find recordings

  $recordings = mysqlfetch ($mysql, "select concat(recording.work_id,'-',recording.spotify_albumid,'-',recording.subset) as id, recording.observation as observation, recording.subset, recording.verified, recording.spotify_albumid, recording.work_id as work, recording.composer_name as composer_name, recording.work_title as work_title, spotify_imgurl as cover, performer, role from recording, recording_performer, playlist_recording where playlist_id = '{$_REQUEST["id"]}' and recording_performer.work_id = recording.work_id and recording_performer.subset = recording.subset and recording_performer.spotify_albumid = recording.spotify_albumid and playlist_recording.work_id = recording.work_id and playlist_recording.subset = recording.subset and playlist_recording.spotify_albumid = recording.spotify_albumid order by position desc, work asc, recording.spotify_albumid asc, recording.subset asc");

  if (!$recordings)
  {
    // if there are no recordings, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No recordings found");
  }
  else
  {
    // playlist details

    $query = "select playlist.id as id, playlist.name as name, user.name as owner, user.id as owner_id from playlist, user where user_id=user.id and playlist.id = '{$_REQUEST["id"]}'";
    $playlist = mysqlfetch ($mysql, $query);
    $apireturn["playlist"] = Array 
      (
        "id" => $playlist[0]["id"],
        "name" => $playlist[0]["name"],
        "owner" => Array 
          (
            "id" => $playlist[0]["owner_id"],
            "name" => $playlist[0]["owner"]
          )
      );

    // recordings

    // open opus api call

    foreach ($recordings as $rec)
    {
      if ($rec["composer_name"] == "")
      {
        if (is_numeric ($rec["work"])) $worklist[] = $rec["work"];
      }
    }

    if (sizeof ($worklist))
    {
      $obworks = openopusdownparse ("work/list/{$_REQUEST["cid"]}/ids/". implode (",", array_unique ($worklist)). ".json");
    }

    $id = -1;

    foreach ($recordings as $rec)
    {
      if ($lastid != $rec["id"])
      {
        $id = $id + 1;

        if ($rec["composer_name"])
        {
          $vid = slug ($rec["composer_name"]. "-". $rec["work_title"]. "-". $id);
        }
        else
        {
          $vid = slug ($obworks["works"]["w:". $rec["work"]]["composer"]["name"]. "-". $obworks["works"]["w:". $rec["work"]]["title"]. "-". $id);
        }

        $apireturn["recordings"][$vid] = Array
          (
            "spotify_albumid" => $rec["spotify_albumid"],
            "set" => (String) $rec["subset"],
            "cover" => $rec["cover"],
            "observation" => $rec["observation"],
            "verified" => $rec["verified"]
          );
      }

      $apireturn["recordings"][$vid]["performers"][] = Array ("name"=>$rec["performer"],"role"=>$rec["role"]);
      $apireturn["recordings"][$vid]["work"] = Array
        (
          "composer"=>Array
            (
              "id"=>($rec["composer_name"] ? "0" : $obworks["works"]["w:". $rec["work"]]["composer"]["id"]),
              "name"=>($rec["composer_name"] ? $rec["composer_name"] : $obworks["works"]["w:". $rec["work"]]["composer"]["name"]),
              "complete_name"=>($rec["composer_name"] ? $rec["composer_name"] : $obworks["works"]["w:". $rec["work"]]["composer"]["complete_name"]),
              "epoch"=>($rec["composer_name"] ? "None" : $obworks["works"]["w:". $rec["work"]]["composer"]["epoch"])
            ),
           "id"=>$rec["work"],
           "title"=>($rec["work_title"] ? $rec["work_title"] : $obworks["works"]["w:". $rec["work"]]["title"]),
           "genre"=>($rec["work_title"] ? "None" : $obworks["works"]["w:". $rec["work"]]["genre"]),
        );

      $lastid = $rec["id"];
    }

    $apirecordings = $apireturn["recordings"];

    foreach ($apirecordings as $apid => $apirec)
    {
      $apirecordings[$apid]["performers"] = orderperformers ($apirec["performers"]);
      $apirecordings[$apid]["recording_id"] = "wkid-". $apirec["work"]["id"]. "-". $apirec["spotify_albumid"] . "-". slug(implode ("-", arraykeepvalues ($apirecordings[$apid]["performers"], ["name"])));
    }

    ksort ($apirecordings);
    $apireturn["recordings"] = array_values ($apirecordings);

    // checks spotify if recordings are available in the user's market

    if ($_REQUEST["market"])
    {
      foreach ($apireturn["recordings"] as $recs)
      {
          $plids[] = $recs["spotify_albumid"];
      }

      $plidsgr = array_chunk ($plids, 20);
      $token = spotifyauth ();

      foreach ($plidsgr as $plidsp)
      {
        $albids = implode (",", $plidsp);
        $chkalbs = spotifydownparse (SPOTIFYAPI. "/albums/?market={$_REQUEST["market"]}&ids={$albids}", $token);
  
        foreach ($chkalbs["albums"] as $albchk)
        {
            $albschkd[] = $albchk["id"];
        }
      }

      foreach ($apireturn["recordings"] as $recss)
      {
        if (in_array ($recss["spotify_albumid"], $albschkd))
        {
          $apireturn["valid-recordings"][] = $recss;
        }
      }

      $apireturn["recordings"] = $apireturn["valid-recordings"];
      unset ($apireturn["valid-recordings"]);
    }
  }

  if (isset ($apireturn["recordings"]))
  {
    $apireturn["status"]["rows"] = sizeof ($apireturn["recordings"]);
    if ($_REQUEST["market"]) $apireturn["status"]["market"] = $_REQUEST["market"];
    $apireturn["works"] = $obworks["abstract"];

    foreach ($recordings as $rec)
    {
      if ($rec["composer_name"])
      {
        $cn = end (explode (" ", $rec["composer_name"]));
        if (!in_array ($cn, $apireturn["works"]["composers"]["names"]))
        {
          $apireturn["works"]["composers"]["portraits"][] = OPENOPUS_DEFCOMP;
          $apireturn["works"]["composers"]["names"][] = $cn;
          $apireturn["works"]["works"]["rows"] += 1;
        }
      }
    }

    $apireturn["works"]["composers"]["rows"] = sizeof ($apireturn["works"]["composers"]["names"]);
  }

  if ($_REQUEST["market"])
  {
    echo savecache ("/recording/{$_REQUEST["market"]}/list/playlist/{$_REQUEST["id"]}.json", apireturn ($apireturn));
  }
  else
  {
    echo savecache ("/recording/list/playlist/{$_REQUEST["id"]}.json", apireturn ($apireturn));
  }
