<?
  include_once ("../../../lib/inc.php");
  global $forbidden_labels, $historical_labels;

  $goext = NOCACHE;

  if (!postcheck ($_REQUEST, ["work"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    // parameters ok

    $apireturn["status"] = Array ("success"=>"true");

    $recordings = mysqlfetch ($mysql, "select recording.id, compilation, label from recording where work_id = {$_REQUEST["work"]} and spotify_absent = 0 order by rand() limit 1");

    if (!$recordings)
    {
      // no recording found on the database, fetch externally

      $apireturn["status"]["source"] = "ext";
      $goext = true;
    }
    else
    {
      // it's all on the db

      $apireturn["status"]["source"] = "db";

      foreach ($recordings as $rec)
      {
        if (!in_array ($rec["label"], $forbidden_labels))
        {
          $apireturn["recording"] = Array
            (
              "id" => $rec["id"],
              "historical" => (in_array ($rec["label"], $historical_labels)) ? "true" : "false",
              "compilation" => ($rec["compilation"]) ? "true" : "false"
            );
        }
      }
    }

    // not found, fetch externally

    if ($goext)
    {
      $work = mysqlfetch ($mysql, "select uni_id from work where id = '{$_REQUEST["work"]}'");
      $recs = fetchrecordings ($_REQUEST["work"], $work[0]["uni_id"]);

      // randomly pick one recording

      $rec = $recs[mt_rand (0, sizeof ($recs))];
      
      $apireturn["recording"] = Array
            (
              "id" => $rec["id"],
              "historical" => (in_array ($rec["label"], $historical_labels)) ? "true" : "false",
              "compilation" => ($rec["compilation"]) ? "true" : "false"
            );
    }
  }

  if ($apireturn["recording"])
  {
    $_REQUEST["id"] = $apireturn["recording"]["id"];
    unset ($apireturn);
    include_once ("detail.phtml");
  }
  else
  {
    echo apireturn ($apireturn);
  }