<?
  include_once ("../../../lib/inc.php");

  // identity check

  if (!postcheck ($_REQUEST, ["wid", "aid", "set"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    // select the shorted url for the recording

    $query = "select id from shortrec where work_id = '{$_REQUEST["wid"]}' and spotify_albumid = '{$_REQUEST["aid"]}' and subset = '{$_REQUEST["set"]}'";
    $id = mysqlfetch ($mysql, $query);

    // it doesn't exit, so... inserting the recording into the short urls table

    if (!$id)
    {
        $query = "insert into shortrec (work_id, spotify_albumid, subset) values ('{$_REQUEST["wid"]}', '{$_REQUEST["aid"]}', '{$_REQUEST["set"]}')";
        mysqli_query ($mysql, $query);
        $retid = mysqli_insert_id ($mysql);
        $status = "insert";
    }
    else
    {
        $retid = $id[0]["id"];
        $status = "select";
    }

    $apireturn["status"]["success"] = "true";
    $apireturn["recording"] = Array ("work_id"=>$_REQUEST["wid"], "spotify_albumid"=>$_REQUEST["aid"], "set"=>(String) $_REQUEST["set"], "id" => strval ($retid), "operation" => $status);
  }

  echo savecache ("/recording/shorturl/work/{$_REQUEST["wid"]}/album/{$_REQUEST["aid"]}/{$_REQUEST["set"]}.json", apireturn ($apireturn));
