<?
  include_once ("../../../../lib/inc.php");

  $apireturn["request"]["type"] = "favorite";
  $apireturn["request"]["item"] = "fav";

  // listing works

  $sql = "select work_id from user_work where composer_id = '{$_REQUEST["cid"]}' and user_id='{$_REQUEST["uid"]}' and favorite=1";
  $works = mysqlfetch ($mysql, $sql);

  //echo $sql;

  if (!$works)
  {
    // if no works exist, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No works found");
  }
  else
  {
    // there are works, fetch'em on the Open Opus API

    foreach ($works as $work)
    {
      $worklist[] = $work["work_id"];
    }

    $obworks = openopusdownparse ("work/list/composer/{$_REQUEST["cid"]}/ids/". implode (",", $worklist). "/search/{$_REQUEST["search"]}.json");

    $apireturn["status"] = Array ("success"=>"true", "source"=>"db");
    $apireturn["composer"] = $obworks["composer"];
    $apireturn["works"] = $obworks["works"];
    $apireturn["status"]["rows"] = sizeof ($obworks["works"]);
  }

  if ($_REQUEST["search"])
  {
    echo savecache ("/user/{$_REQUEST["uid"]}/composer/{$_REQUEST["cid"]}/work/fav/search/{$_REQUEST["search"]}.json", apireturn ($apireturn));
  }
  else
  {
    echo savecache ("/user/{$_REQUEST["uid"]}/composer/{$_REQUEST["cid"]}/work/fav.json", apireturn ($apireturn));
  }
  