<?
  include_once ("../../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["rid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $query = "insert into user_recording (user_id, recording_id, favorite) values ('{$_REQUEST["id"]}', '{$_REQUEST["rid"]}', 0)
                  on duplicate key update favorite = 0";

      mysqli_query ($mysql, $query);

      $apireturn["status"]["success"] = "true";
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["recording"]["id"] = $_REQUEST["rid"];
  }

  shell_exec ("rm ". WEBDIR. "/user/{$_REQUEST["id"]}/ -rf");
  echo apireturn ($apireturn);
