<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["tag", "wid", "aid", "set", "cover", "performers"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    // inserting the recording into the recording abstract database

    insertrecording ($_REQUEST);

    // update creation

    foreach (["verified", "compilation", "wrongdata", "badquality"] as $val)
    {
      $set[] = $val. " = ". ($_REQUEST["tag"] == $val ? 1 : 0);
    }

    // updating the recording 

    $query = "update recording set ". implode (",", $set). " where work_id = '{$_REQUEST["wid"]}' and spotify_albumid = '{$_REQUEST["aid"]}' and subset = '{$_REQUEST["set"]}'";
    mysqli_query ($mysql, $query);

    $apireturn["status"]["success"] = "true";
    $apireturn["recording"] = Array ("work_id"=>$_REQUEST["wid"], "spotify_albumid"=>$_REQUEST["aid"], "set"=>(String) $_REQUEST["set"], $_REQUEST["tag"] => 1);

    cachepurge ([
      "/recording/list/work/{$_REQUEST["wid"]}/",
      "/recording/detail/work/{$_REQUEST["wid"]}/album/{$_REQUEST["aid"]}/"
    ]);
  }

  echo apireturn ($apireturn);
