<?
  include_once ("../../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["pid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $query = "delete from user_playlist where user_id='{$_REQUEST["id"]}' and playlist_id='{$_REQUEST["pid"]}'";

      mysqli_query ($mysql, $query);
      $op = mysqli_affected_rows ($mysql);

      if ($op >= 1)
      {
        $apireturn["status"]["success"] = "true";
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }

      $apireturn["list"] = userplaylists ($_REQUEST["id"]);
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["playlist"]["id"] = $_REQUEST["pid"];
  }

  cachepurge ([
    "/recording/list/playlist/{$_REQUEST["pid"]}.json",
    "/user/{$_REQUEST["id"]}/*"
  ]);
  
  echo apireturn ($apireturn);
