<?
  include_once ("../../../../lib/inc.php");
  
  $goquery = true;

  // type of request

  $apireturn["request"]["type"] = "fav";

  // listing composers

  if ($goquery)
  {
    $composers = mysqlfetch ($mysql, "select composer_id from user_composer where user_id = '{$_REQUEST["id"]}' and favorite=1");

    if (!$composers)
    {
      // if no composers exist, return an error

      $apireturn["status"] = Array ("success"=>"false", "error"=>"No composers found");
    }
    else
    {
      // there are composers, fetch'em on the Open Opus API

      foreach ($composers as $comp)
      {
        $complist[] = $comp["composer_id"];
      }

      $obcomposers = openopusdownparse ("composer/list/ids/". implode (",", $complist). ".json");
    
      $apireturn["status"]["success"] = "true";
      $apireturn["status"]["source"] = "db";
      $apireturn["composers"] = $obcomposers["composers"];
      $apireturn["status"]["rows"] = sizeof ($apireturn["composers"]);
    }
  }

  echo savecache ("/user/{$_REQUEST["id"]}/composer/fav.json", apireturn ($apireturn));
