<?
  include_once ("../../../../lib/inc.php");
  
  $goquery = true;

  // type of request

  $apireturn["request"]["type"] = "fav";

  // listing composers

  if ($goquery)
  {
    $composers = mysqlfetch ($mysql, "select id, name, complete_name, birth, death, epoch from composer, user_composer where user_id = '{$_REQUEST["id"]}' and id = composer_id and favorite=1 order by name asc");

    if (!$composers)
    {
      // if no composers exist, return an error

      $apireturn["status"] = Array ("success"=>"false", "error"=>"No composers found");
    }
    else
    {
      // there are composers, go list'em

      $apireturn["status"]["success"] = "true";
      $apireturn["status"]["source"] = "db";
      $apireturn["composers"] = $composers;
      $apireturn["status"]["rows"] = sizeof ($apireturn["composers"]);
    }
  }

  echo savecache ("/user/{$_REQUEST["id"]}/composer/fav.json", apireturn ($apireturn));
