<?
  include_once ("../../../../lib/inc.php");

  // filtering

  if (!postcheck ($_REQUEST, ["id"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    // everything ok

    $from = ["work", "composer"];
    $where[] = "composer.id=work.composer_id";
    $apireturn["criteria"] = [];

    if ($_REQUEST["genre"])
    {
      if ($_REQUEST["genre"] != "All")
      {
        $where[] = "genre = '{$_REQUEST["genre"]}'";
        $apireturn["criteria"][] = ["genre"=>$_REQUEST["genre"]];
      }
    }

    if ($_REQUEST["epoch"])
    {
      if ($_REQUEST["epoch"] != "All")
      {
        $where[] = "epoch = '{$_REQUEST["epoch"]}'";
        $apireturn["criteria"][] = ["epoch"=>$_REQUEST["epoch"]];
      }
    }

    if ($_REQUEST["composer"])
    {
      if ($_REQUEST["composer"] == "fav")
      {
        $from[] = "user_composer";
        $where[] = "user_composer.composer_id = composer.id";
        $where[] = "user_composer.favorite = 1";
        $where[] = "user_composer.user_id = '{$_REQUEST["id"]}'";
        $apireturn["criteria"][] = ["composer"=>$_REQUEST["composer"]];
      }
      else if ($_REQUEST["composer"] != "All")
      {
        $where[] = "composer_id = '{$_REQUEST["composer"]}'";
        $apireturn["criteria"][] = ["composer"=>$_REQUEST["composer"]];
      }
    }

    if ($_REQUEST["work"])
    {
      if ($_REQUEST["work"] == "fav")
      {
        $from[] = "user_work";
        $where[] = "user_work.work_id = work.id";
        $where[] = "user_work.favorite = 1";
        $where[] = "user_work.user_id = '{$_REQUEST["id"]}'";
        $apireturn["criteria"][] = ["work"=>$_REQUEST["work"]];
      }
      else if ($_REQUEST["work"] != "All")
      {
        $where[] = "work.id = '{$_REQUEST["work"]}'";
        $apireturn["criteria"][] = ["work"=>$_REQUEST["work"]];
      }
    }

    // try to find suitable works in the database

    $query = "select work.id, composer.id as composer from ". implode (",", $from). " where ". implode (" and ", $where). " order by rand() limit 40";
    $work = mysqlfetch ($mysql, $query);
    
    if (!$work)
    {
      // if no work exists, return an error

      $apireturn["status"] = Array ("success"=>"false", "error"=>"No works found");
    }
    else
    {
      // there are works, try to find recordings in the database

      $apireturn["status"] = Array ("success"=>"true");
      $apireturn["works"] = $work;
    }
  }

  echo apireturn ($apireturn);
