<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["wid", "aid", "set", "pid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // checking playlist ownership

      $query = "select user_id from playlist where id = '{$_REQUEST["pid"]}'";
      $check = mysqlfetch ($mysql, $query);

      if ($check[0]["user_id"] == $_REQUEST["id"])
      {
        // removing the recording from the playlist

        $query = "delete from playlist_recording where playlist_id = '{$_REQUEST["pid"]}' and spotify_albumid = '{$_REQUEST["aid"]}' and work_id = '{$_REQUEST["wid"]}' and subset = '{$_REQUEST["set"]}'";

        mysqli_query ($mysql, $query);

        $apireturn["status"]["success"] = "true";
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }
      
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["playlist"]["id"] = $_REQUEST["pid"];
      $apireturn["recording"] = Array ("work_id"=>$_REQUEST["wid"], "spotify_albumid"=>$_REQUEST["aid"], "set"=>(String) $_REQUEST["set"]);
      $apireturn["list"] = userplaylists ($_REQUEST["id"]);
  }

  shell_exec ("rm ". WEBDIR. "/recording/list/playlist/{$_REQUEST["pid"]}.json");
  shell_exec ("rm ". WEBDIR. "/user/{$_REQUEST["id"]}/ -rf");
  echo apireturn ($apireturn);
