<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["rid", "work_id"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      mysqli_query ($mysql, "delete from recording where id={$_REQUEST["rid"]} and work_id={$_REQUEST["work_id"]}");
      $op = mysqli_affected_rows ($mysql);

      if ($op >= 1)
      {
        $apireturn["status"]["success"] = "true";
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }

      $apireturn["status"]["deleted_rows"] = $op;
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["recording"]["id"] = $_REQUEST["rid"];

      cachepurge ([
        "/recording/list/work/{$_REQUEST["work_id"]}.json",
        "/recording/detail/{$_REQUEST["rid"]}.json"
      ]);
  }

  echo apireturn ($apireturn);
