<?
  include_once ("../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["pid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // checking playlist ownership

      $query = "select user_id from playlist where id = '{$_REQUEST["pid"]}'";
      $check = mysqlfetch ($mysql, $query);

      if ($check[0]["user_id"] == $_REQUEST["id"])
      {
        // removing the recordings from the playlist

        if ($_REQUEST["rid"])
        {
          $recs = explode (",", $_REQUEST["rid"]);

          foreach ($recs as $rec)
          {
            $recp = explode ("-", $rec);
            $recq[] = "('{$recp[1]}','{$recp[2]}')";
            //$recq[] = "('{$recp[0]}','{$recp[1]}','{$recp[2]}')";
          }
          
          $query = "delete from playlist_recording where playlist_id = '{$_REQUEST["pid"]}' and (work_id, spotify_albumid) in (". implode (",", $recq). ")";
          
          mysqli_query ($mysql, $query);
        }
        
        // renaming the playlist

        if ($_REQUEST["name"])
        {
          $query = "update playlist set name = '{$_REQUEST["name"]}' where id = '{$_REQUEST["pid"]}' and user_id = '{$_REQUEST["id"]}'";
          mysqli_query ($mysql, $query);
        }

        $apireturn["status"]["success"] = "true";
      }
      else
      {
        $apireturn["status"]["success"] = "false";
      }
      
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["playlist"]["id"] = $_REQUEST["pid"];
      $apireturn["list"] = playlists ($_REQUEST["id"]);
  }

  shell_exec ("rm ". WEBDIR. "/recording/*/list/playlist/{$_REQUEST["pid"]}.json");
  shell_exec ("rm ". WEBDIR. "/recording/list/playlist/{$_REQUEST["pid"]}.json");
  shell_exec ("rm ". WEBDIR. "/user/{$_REQUEST["id"]}/ -rf");
  echo apireturn ($apireturn);
