<?
  include_once ("../../lib/inc.php");

  // initializing

  define ("DATAPATH", "../../../../data");
  define ("JASAO", DATAPATH. "/db.json");
  define ("IMGPATH", "/var/www/concertmaster/cmas.me/html/img/portraits");

  // reading the original json file

  $json = file_get_contents (JASAO);
  $array = json_decode ($json, true);

  // making works and composers apart

  function work_or_composer ($value)
  {
    if (array_key_exists ("composer_id", $value))
    {
      global $composerarray;
      $composerarray[] = $value;
    }
    else if (array_key_exists ("work_id", $value))
    {
      global $workarray;
      $workarray[$value["work_composer"]][] = $value;
    }
  }

  array_walk ($array, "work_or_composer");

  foreach ($composerarray as $composer)
  {
    $name = slug ($composer["composer_name"]);
    echo $name. "\n";
    rename (IMGPATH. "/{$composer["composer_id"]}.jpg", IMGPATH. "/{$name}.jpg");
  }
