<?
  include_once ("../inc.php");

  // constantes locais

  define ("JASAO", "./db.json");
  $importall = false;

  // abrindo json original

  $json = file_get_contents (JASAO);
  $array = json_decode ($json, true);

  // separando obras de compositores

  function work_or_composer ($value)
  {
    if (array_key_exists ("composer_id", $value))
    {
      global $composerarray;
      $composerarray[] = $value;
    }
    else if (array_key_exists ("work_id", $value))
    {
      global $workarray;
      $workarray[$value["work_composer"]][] = $value;
    }
  }

  array_walk ($array, "work_or_composer");

  // gravando os compositores na base

  function save_composer ($value)
  {
    global $mysql, $importall, $workarray;

    // para testes

    $willimport = Array
    (
      "Bruckner",
      "Sibelius",
      "Nielsen",
      "Brahms"
    );

    // procura os compositores no Rovi

    if (in_array ($value["composer_name"], $willimport) || $importall)
    {
      $api = rovidownparse (ROVISEARCH. "/search?filter=genreid:MA0000002521&entitytype=artist&query=". urlencode ($value["composer_fullname"]), "json");

      // gravando na base

      $insert = Array
      (
        "name" => $value["composer_name"],
        "complete_name" => $api["searchResponse"]["results"][0]["name"]["name"],
        "birth" => $api["searchResponse"]["results"][0]["name"]["birth"]["date"],
        "death" => $api["searchResponse"]["results"][0]["name"]["death"]["date"],
        "epoch" => $value["composer_period"],
        "country" => $api["searchResponse"]["results"][0]["name"]["country"],
        "rovi_id" => $api["searchResponse"]["results"][0]["id"]
      );

      print_r ($insert);
      mysqlinsert ($mysql, "composer", $insert);
      $cid = mysqli_insert_id ($mysql);
      usleep (250000);

      // procura as obras do compositor

      $api = rovidownparse (ROVIBASE. "/name/compositions?nameid={$insert["rovi_id"]}", "json");

      foreach ($api["compositions"] as $wapi)
      {
        // pega so o ano da composicao

        $pattern = '/(^([0-9]+)-)/i';
        $replacement = '$2';
        preg_match ($pattern, $wapi["compositionDate"], $matches);
        if (is_array ($matches))
        {
          if (count($matches) >= 2)
          {
            $wapi["compositionDate"] = $matches[2]."-01-01";
          }
        }

        $insert = Array
        (
          "composer_id" => $cid,
          "title" => $wapi["title"],
          "genre" => $wapi["genre"]["name"],
          "year" => $wapi["compositionDate"],
          "rovi_id" => $wapi["id"]
        );

        print_r ($insert);
        mysqlinsert ($mysql, "work", $insert);
      }
    }
  }

  array_walk ($composerarray, "save_composer");
